#!/usr/bin/env node
/**
 * Copy the deployment URL from the repo-root .env.local into each app.
 *
 * `npx convex dev` writes .env.local at the REPO ROOT, because convex/ lives
 * there. Next only reads .env.local from the app directory — and passing the
 * value through next.config's `env` is NOT equivalent: the edge runtime that
 * runs middleware.ts does not reliably receive it, so
 * `convexAuthNextjsMiddleware` sees no deployment URL, auth discovery fails,
 * and `isAuthenticated()` returns false for everyone. A real session exists
 * client-side while every protected route bounces to sign-in.
 *
 * One source of truth (the root file, owned by the Convex CLI), copied to
 * where Next can actually see it. Runs before dev and before build.
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const source = join(repoRoot, ".env.local");

if (!existsSync(source)) {
  console.log("sync-env: no root .env.local — run `npx convex dev` first. Skipping.");
  process.exit(0);
}

const env = {};
for (const line of readFileSync(source, "utf8").split("\n")) {
  const match = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
  if (!match) continue;
  const [, key, rawValue] = match;
  // Convex appends a trailing "# team: ... project: ..." comment.
  env[key] = rawValue.replace(/^["']|["']$/g, "").split(" #")[0].trim();
}

const convexUrl = env.CONVEX_URL;
if (!convexUrl) {
  console.log("sync-env: root .env.local has no CONVEX_URL. Skipping.");
  process.exit(0);
}

/**
 * NEXT_PUBLIC_CONVEX_URL is public by necessity: the office runs a browser
 * Convex client, and the middleware reads the same variable. It is a
 * deployment address, not a secret — every request to it is still
 * authenticated and every function still re-derives its own tenant.
 */
const apps = [
  { dir: "apps/office", keys: { CONVEX_URL: convexUrl, NEXT_PUBLIC_CONVEX_URL: convexUrl } },
  /*
   * apps/sites is server-rendered only and never ships a Convex client.
   *
   * REVALIDATE_SECRET must be carried too, and this is the only place that can
   * do it: this script REWRITES each target file, so a hand-added value here
   * would be silently erased on the next `predev`. Without it the revalidate
   * route fails closed, every config publish appears to do nothing, and the
   * site only catches up on the one-hour fallback — a failure with no error
   * anywhere. It is optional on purpose: unset is survivable, and the route
   * refusing to serve is better than an open endpoint.
   */
  { dir: "apps/sites", keys: { CONVEX_URL: convexUrl, REVALIDATE_SECRET: env.REVALIDATE_SECRET } },
];

for (const app of apps) {
  const target = join(repoRoot, app.dir, ".env.local");
  const body = [
    "# GENERATED by scripts/sync-env.mjs from the repo-root .env.local.",
    "# Do not edit. Do not commit. Run `npx convex dev` to change the source.",
    ...Object.entries(app.keys)
      .filter(([, v]) => v !== undefined && v !== "")
      .map(([k, v]) => `${k}=${v}`),
    "",
  ].join("\n");

  const existing = existsSync(target) ? readFileSync(target, "utf8") : null;
  if (existing !== body) {
    writeFileSync(target, body);
    console.log(`sync-env: wrote ${app.dir}/.env.local`);
  }
}
